AllCops:
  TargetRubyVersion: 2.3

# I prefer no empty line between magic comment and requires.
Layout/EmptyLineAfterMagicComment:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

# I prefer to put two spaces before inline comment, Rubocop does not allow to
# set exception for this.
Layout/ExtraSpacing:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/AbcSize:
  Max: 36

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/FileName:
  Exclude:
    - 'lib/asciidoctor-rouge.rb'

# I don't use guard clause when line would be too long.
Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

Style/FormatString:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - Gemfile*
    - Rakefile
    - '*.gemspec'

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RedundantFreeze:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
