dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - jruby
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
env:
  global:
    secure:  # FIXME: CODACY_PROJECT_TOKEN
script:
  - bundle exec rake spec
  - bundle exec rake rubocop
deploy:
  provider: rubygems
  api_key:
    secure: FIXME
  on:
    rvm: 2.4
    tags: true
